contacts:
  - "09*********"
  - "09*********"
alerts:
  - alertname: "testalert1"
    alertpath: "/opt/testalert1.sh"
    runcommand: true
    executinguser: "root"
    serverip: "x.x.x.x"
  - alertname: "testalert2"
    alertpath: "/opt/testalert2.sh"
    runcommand: false
    executinguser: "root"
    serverip: "x.x.x.x"
runcommands: False
smsgateway:
  url: "http://**.**.**.**:****/*****"
  username: "****"
  password: "****"

