contacts:
  - "09*********"
  - "09*********"
containerid: ""
restarturl: ""
alertname: ""
runcommands: False
smsgateway:
  url: "http://**.**.**.**:****/*****"
  username: "****"
  password: "****"

