version: "3.9"
services:
  smsnotification:
    image: hosted-registry.platform2.local/smsalerter:2
    container_name: smsnotifsender
    ports:
      - "5000:5000"
    volumes:
      - "./config/configs.yaml:/configs.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock"
